nome = input('Digite um funcionário:')
empresa = input('Digite a instituição:')
qtde_funcionarios = int(input('Digite a qtde de funcionários:'))
mediaaMensalidade = float(input('Digite a média da mensalidade:'))
print(nome + ' trabalha na empreda ' + empresa)
print('possui: ', qtde_funcionarios, 'funcionarios. ' )
print('A média de mensalidade é de: ' + str(mediaaMensalidade))
print('==============Verifique os tipos de dados abaixo:===========')
print('O tipo de dado da variavel [nome] é: ',type(nome))
print('O tipo de dado da variavel [empresa] é: ',type(empresa))
print('O tipo de dado da variavel [qtda_funcionarios] é: ',type(qtde_funcionarios))
print('O tipo de dado da variavel [mediaMensalidade] é: ',type(mediaaMensalidade))
